-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Weapon 1"] = "Weapon1", 
	["Weapon 2"] = "Offhand1", 
	["Helmet"] = "Helm1", 
	["Amulet"] = "Amulet1", 
	["Ring 1"] = "Ring1", 
	["Ring 2"] = "Ring2", 
	["Gloves"] = "Gloves1", 
	["Boots"] = "Boots1", 
	["Belt"] = "Belt1", 
	["Flask 1"] = "Flask1", 
	["Weapon 1 Swap"] = "Weapon2", 
	["Weapon 2 Swap"] = "Offhand2", 
	["Trinket"] = "Trinket1", 
	["Ring 3"] = "Ring3", 
	["Weapon3"] = "Weapon3", 
	["Offhand3"] = "Offhand3", 
	["Body Armour"] = "BodyArmour1", 
}