name: Backport changes to PoB1

on:
    pull_request:
        types: [closed]

jobs:
    backport:
        if: contains(github.event.pull_request.labels.*.name, 'pob1')
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.event.pull_request.merged }}
            - name: Notify PathOfBuilding repo
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${{ secrets.WIRES77_PAT }}
                repository: ${{ github.repository_owner }}/PathOfBuilding
                event-type: port-changes
                client-payload: '{"patch_url": "${{ github.event.pull_request.patch_url }}", "msg": "Apply changes from ${{ github.event.pull_request.html_url }}", "id": ${{ github.event.pull_request.number }}}'

